### ISSUE TITLE
Doc typo: "config.resovle"

### ISSUE THREAD

**Issue by tomxtobin** [jonschlinkert/config-file#3]
In the `index.js` doc comments, `config.resovle` should be `config.resolve`. (This is visible in `README.md`, too.)

FWIW, I tried making a pull request, but I couldn't get `verb-cli` working because of verbose/verb#62.

**Comment by jonschlinkert** [comment]
thanks for the heads up! I'm working on that verb issue now, trying to refactor it to the basics so we don't have these issues anymore. If you'd like to do a pr to just edit the `.verb.md` file that would be great, I can build it. Or I'd be happy to fix the typo, whatever you prefer

**Comment by tomxtobin** [comment]
No problem! Just pushed to #4.
